package app.saveit.core.net

/** Writes the Netscape cookie-file format yt-dlp reads with `--cookies`. */
object NetscapeCookies {
    fun fromHeader(domain: String, cookieHeader: String, expiresEpochSec: Long = System.currentTimeMillis() / 1000 + 365L * 24 * 3600): String {
        val d = "." + domain.trimStart('.')
        val sb = StringBuilder("# Netscape HTTP Cookie File\n# Generated by SaveIt. Do not share this file.\n\n")
        cookieHeader.split(';').forEach { part ->
            val name = part.substringBefore('=').trim()
            val value = part.substringAfter('=', "").trim()
            if (name.isNotEmpty() && !name.contains('\t') && !value.contains('\t') && !value.contains('\n')) {
                sb.append(d).append("\tTRUE\t/\tTRUE\t").append(expiresEpochSec).append('\t')
                    .append(name).append('\t').append(value).append('\n')
            }
        }
        return sb.toString()
    }

    /** Merges several domains' cookies into one file. */
    fun build(entries: Map<String, String>): String {
        val header = "# Netscape HTTP Cookie File\n# Generated by SaveIt. Do not share this file.\n\n"
        return header + entries.entries.joinToString("") { (domain, cookies) ->
            fromHeader(domain, cookies).lineSequence().filter { it.isNotBlank() && !it.startsWith("#") }.joinToString("\n", postfix = "\n")
        }
    }
}
